#+title: README
#+author: Troy Fischer
#+startup: overview

* Dotfiles
Organizing dotfiles in this repository for quick start up time on a fresh computer. Using [[https://www.gnu.org/software/stow/][GNU Stow]] to create the symbolic links.
* Mac
** Install Homebrew
#+begin_src sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#+end_src
** Programs
*** Brewfile
Tangle the Brewfile
#+begin_src sh
brew bundle
brew bundle --file=/path/to/file
#+end_src

#+begin_src sh :tangle Brewfile
tap "homebrew/cask"
tap "homebrew/core"
#+end_src
**** Browser
***** Brave
#+begin_src sh :results silent :tangle Brewfile
cask "brave-browser"
#+end_src
**** Terminal
#+begin_src sh :tangle Brewfile
cask "alacritty"
cask "kitty"
#+end_src
**** Fonts
#+begin_src sh :tangle Brewfile
tap "homebrew/cask-fonts"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-overpass"
cask "font-hack"
cask "font-cascadia-code"
cask "font-cascadia-mono"
cask "font-ibm-plex"
cask "font-source-code-pro"
cask "font-monaspace"
#+end_src
**** Navigation
Need at least one of these
***** [[https://github.com/nikitabobko/AeroSpace][Aerospace]]
#+begin_src sh :tangle Brewfile
brew "aerospace"
#+end_src
***** [[https://www.keyboardmaestro.com/main/][Keyboard Maestro]]
#+begin_src sh :tangle Brewfile
cask "keyboard-maestro"
#+end_src
**** Programming
***** Python
#+begin_src sh :tangle Brewfile
brew "basedpyright"
brew "ruff"
#+end_src
***** Lua
#+begin_src sh :tangle Brewfile
brew "lua"
brew "stylua"
#+end_src
** Doom Emacs
[[https://github.com/doomemacs/doomemacs][Install Doom Emacs]]
#+begin_src sh
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
#+end_src

Assuming my dotfiles have added ~/.config/emacs/bin to the PATH.
#+begin_src sh
doom install
#+end_src
* Chrome Extensions
+ [[https://chrome.google.com/webstore/detail/browserpass/naepdomgkenhinolocfifgehidddafch?hl=en][Browserpass]]
+ [[https://chrome.google.com/webstore/detail/df-tube-distraction-free/mjdepdfccjgcndkmemponafgioodelna?hl=en][Distraction Free Youtube]]
+ [[https://chrome.google.com/webstore/detail/youtube-playback-speed-co/hdannnflhlmdablckfkjpleikpphncik/reviews?hl=en][Youtube Speed Playback Control]]
+ [[https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en-US][Dark Reader]]
+ [[https://chrome.google.com/webstore/detail/united-by-zero/cnicehoklaonpoobcjbagnmbchlacmpk][United By Zero]]
+ [[https://chrome.google.com/webstore/detail/tab-groups-extension/nplimhmoanghlebhdiboeellhgmgommi?hl=en#:~:text=Tab%20Groups%20Extension&text=Automatically%20group%20tabs%2C%20save%20tabs,tabs%20through%20custom%20matching%20rules.][Tab Groups]]
+ [[https://chrome.google.com/webstore/detail/tab-suspender/fiabciakcmgepblmdkmemdbbkilneeeh/related?hl=en][Tab Suspender]]
* Issues
** Browserpass
*** Linux
I've had issues getting browserpass to work on some of my recent installs. Solved via this link [[https://github.com/browserpass/browserpass-extension/issues/158][github-fix]].

Specifically this comment (may need modification depending on the browser in use):
#+begin_src sh
sudo mkdir -p /etc/opt/chrome/native-messaging-hosts/
sudo ln -s /etc/chromium/native-messaging-hosts/com.github.browserpass.native.json  /etc/opt/chrome/native-messaging-hosts/com.github.browserpass.native.json
#+end_src
*** Mac
**** Install
- [[https://github.com/browserpass/browserpass-extension][Browserpass Extension]]
- [[https://github.com/browserpass/browserpass-native][Browserpass Native]]
**** Config
Had to explicitly set a few things in [[file:~/.gnupg/][.gnupg]].

In [[file:~/.gnupg/gpg.conf][gpg.conf]]
#+begin_src conf
use-agent
#+end_src

In [[file:~/.gnupg/gpg-agent.conf][gpg-agent.conf]]
#+begin_src conf
pinentry-program /usr/local/bin/pinentry-mac
#+end_src
or
#+begin_src conf
pinentry-program /opt/homebrew/bin/pinentry-mac
#+end_src

To restart the gpg agent
#+begin_src sh
gpgconf --kill gpg-agent
#+end_src
** Emacs Native Comp on apple silicone chips
- [[https://github.com/d12frosted/homebrew-emacs-plus/issues/562][Solution]]
* Notes
** Running Behave Tests
[[https://stackoverflow.com/questions/52725150/how-to-debug-behave-bdd-scenario-using-python-debugger-and-visual-studio-code][dap debug setup for behave tests]]
** Doom Emacs Misc Notes
*** TODO Doom's ~packages.el~ question/issue
Using something like
#+begin_src emacs-lisp :tangle no
(package! some-random-package)
#+end_src
in ~packages.el~ *does not* necessarily pull the package from its latest commit from github. For example with the [[https://github.com/kaiwk/leetcode.el][leetcode.el]] package I had to go to the straight repo, pull the latest code from origin, delete the build artifacts and ~doom sync~ + restart to get the correct code.

Not sure if that is because github is not the default or what. It pulled the latest tag which had code from 2+ years ago.
