#+title: README
#+author: Troy Fischer

* Dotfiles
Organizing dotfiles in this repository for quick start up time on a fresh computer. Using [[https://www.gnu.org/software/stow/][GNU Stow]] to create the symbolic links.
* Mac
** Install Homebrew
#+begin_src sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#+end_src
** Programs
*** General
#+name: programs
#+begin_src sh
echo \
bat \
cmake \
fd \
gcc \
gnupg \
mactex \
neovim \
node \
pandoc \
pass \
pass-otp \
pinentry \
pinentry-mac \
pipenv \
qmk \
ripgrep \
sassc \
sqlite \
stow \
tmux \
#+end_src

#+begin_src sh :var programs=programs :results silent
brew install $programs
#+end_src
*** Browser
**** Brave
#+begin_src sh :results silent
brew install --cask brave-browser
#+end_src
*** Terminal
#+begin_src
brew install --cask alacritty kitty
#+end_src
*** Fonts
#+begin_src sh
brew tap homebrew/cask-fonts
brew install --cask font-fira-code font-fira-code-nerd-font font-jetbrains-mono font-jetbrains-mono-nerd-font font-overpass
#+end_src
** Doom Emacs
[[https://github.com/doomemacs/doomemacs][Install Doom Emacs]]
#+begin_src sh
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
#+end_src

Assuming my dotfiles have added ~/.config/emacs/bin to the PATH.
#+begin_src sh
doom install
#+end_src
* Chrome Extensions
+ [[https://chrome.google.com/webstore/detail/browserpass/naepdomgkenhinolocfifgehidddafch?hl=en][Browserpass]]
+ [[https://chrome.google.com/webstore/detail/df-tube-distraction-free/mjdepdfccjgcndkmemponafgioodelna?hl=en][Distraction Free Youtube]]
+ [[https://chrome.google.com/webstore/detail/youtube-playback-speed-co/hdannnflhlmdablckfkjpleikpphncik/reviews?hl=en][Youtube Speed Playback Control]]
+ [[https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en-US][Dark Reader]]
+ [[https://chrome.google.com/webstore/detail/united-by-zero/cnicehoklaonpoobcjbagnmbchlacmpk][United By Zero]]
+ [[https://chrome.google.com/webstore/detail/tab-groups-extension/nplimhmoanghlebhdiboeellhgmgommi?hl=en#:~:text=Tab%20Groups%20Extension&text=Automatically%20group%20tabs%2C%20save%20tabs,tabs%20through%20custom%20matching%20rules.][Tab Groups]]
+ [[https://chrome.google.com/webstore/detail/tab-suspender/fiabciakcmgepblmdkmemdbbkilneeeh/related?hl=en][Tab Suspender]]
* Issues
** Browserpass
*** Linux
I've had issues getting browserpass to work on some of my recent installs. Solved via this link [[https://github.com/browserpass/browserpass-extension/issues/158][github-fix]].

Specifically this comment (may need modification depending on the browser in use):
#+begin_src sh
sudo mkdir -p /etc/opt/chrome/native-messaging-hosts/
sudo ln -s /etc/chromium/native-messaging-hosts/com.github.browserpass.native.json  /etc/opt/chrome/native-messaging-hosts/com.github.browserpass.native.json
#+end_src
*** Mac
**** Install
[[https://github.com/browserpass/browserpass-extension][Browserpass Extension]]
[[https://github.com/browserpass/browserpass-native][Browserpass Native]]
**** Config
Had to explicitly set a few things in [[file:~/.gnupg/][.gnupg]].

In [[file:~/.gnupg/gpg.conf][gpg.conf]]
#+begin_src conf
use-agent
#+end_src

In [[file:~/.gnupg/gpg-agent.conf][gpg-agent.conf]]
#+begin_src conf
pinentry-program /usr/local/bin/pinentry-mac
#+end_src

To restart the gpg agent
#+begin_src sh
gpgconf --kill gpg-agent
#+end_src
** Emacs Native Comp on apple silicone chips
- [[https://github.com/d12frosted/homebrew-emacs-plus/issues/562][Solution]]
